// -*- C++ -*-  
   std::vector<Int_t> iElecList;
   std::vector<Int_t> iMuonList;
   std::vector<Int_t> iLeptonList;
   std::vector<Int_t> iNeuList;
   std::vector<Int_t> iGammaList;
   std::vector<Int_t> iJetList;
   std::vector<Int_t> ibJetList;
   std::vector<Int_t> iallJetList;
   std::vector<Int_t> irecJetList;
   std::vector<Int_t> irecbJetList;

   std::vector<TLorentzVector*> initList;
   std::vector<TLorentzVector*> wlvList(2);
   std::vector<TLorentzVector*> jetList;
   std::vector<TLorentzVector*> bJetList;
   std::vector<TLorentzVector*> wjjList;
   std::vector<Int_t> iWjjList;
   std::vector<Int_t> jWjjList;