// -*- C++ -*-  
      wlvList.clear();      
      iElecList.clear();
      iMuonList.clear();
      iLeptonList.clear();
      iNeuList.clear();
      iGammaList.clear();
      iJetList.clear();
      ibJetList.clear();
      iallJetList.clear();
      irecJetList.clear();
      irecbJetList.clear();

      jetList.clear();
      bJetList.clear();
      initList.clear();

      iWjjList.clear();
      jWjjList.clear();